from enum import Enum


class MacroEventType(str, Enum):
    INTEREST_RATE_DECISION = "INTEREST_RATE_DECISION"
    CPI = "CPI"
    CORE_CPI = "CORE_CPI"
    PCE = "PCE"
    CORE_PCE = "CORE_PCE"
    NONFARM_PAYROLLS = "NONFARM_PAYROLLS"
    UNEMPLOYMENT_RATE = "UNEMPLOYMENT_RATE"
    GDP = "GDP"
    RETAIL_SALES = "RETAIL_SALES"
    ISM_MANUFACTURING = "ISM_MANUFACTURING"
    ISM_SERVICES = "ISM_SERVICES"
    INITIAL_JOBLESS_CLAIMS = "INITIAL_JOBLESS_CLAIMS"
    FED_CHAIR_SPEECH = "FED_CHAIR_SPEECH"
    OTHER = "OTHER"
